#!/usr/bin/env python3
r"""Emit the NSIS scripts for the Quick Office Windows installers (v1).

v1 POLICY — REPACKAGE, NOT SOURCE BUILD. The from-source Windows engine
(../../windows/BUILD-STATUS.md) is its own lead time; until it lands, the
Windows engine payload is the OFFICIAL LibreOffice stable win64 MSI pinned in
windows-pin.txt, extracted on the Linux build host with msiextract and dressed
with the same Aura layer the Linux debs get: the registry overlay .xcd
(../../registry/install-registry.sh) plus the Aura icon theme zips. Upstream
binaries ship byte-identical — TDF's Authenticode signatures are untouched;
only the OUTER installers are ours. That is why the Windows engine version
(26.2.x) can trail the Linux engine (26.8.x source build).

THREE INSTALLERS, ONE SHARED ENGINE DIR (the Inno thin+download design in
../make-installers.py needs the engine hosted on R2 and a signed fetch chain;
v1 keeps it simple and self-contained):

    QuickDocument-Setup.exe      each carries the FULL engine payload and
    QuickSpreadsheet-Setup.exe   installs it into Program Files\QuickOpen\
    QuickPresentation-Setup.exe  Quick Office ONLY if that exact engine
                                 version is not already there — so the second
                                 and third app installs just add a face.

REFERENCE COUNTING mirrors the Inno design: each app writes itself under
HKLM\Software\QuickOpen\QuickOffice\Apps; an app's uninstaller removes only
its own face while other values remain, and the last app out removes the
engine directory. All installers support silent /S install + uninstall.

    make-windows-installers.py <outdir>
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

APPS = [
    dict(slug="quick-document", exe="QuickDocument", module="--writer",
         comment="A full word processor — write, format and publish",
         mimes=[(".odt", "OpenDocument Text"), (".docx", "Word Document"),
                (".doc", "Word 97-2003 Document"), (".rtf", "Rich Text Document"),
                (".ott", "OpenDocument Text Template")]),
    dict(slug="quick-spreadsheet", exe="QuickSpreadsheet", module="--calc",
         comment="A full spreadsheet — formulas, pivot tables and charts",
         mimes=[(".ods", "OpenDocument Spreadsheet"), (".xlsx", "Excel Workbook"),
                (".xls", "Excel 97-2003 Workbook"), (".csv", "Comma Separated Values"),
                (".ots", "OpenDocument Spreadsheet Template")]),
    dict(slug="quick-presentation", exe="QuickPresentation", module="--impress",
         comment="A full presentation editor — slides, transitions and presenter view",
         mimes=[(".odp", "OpenDocument Presentation"),
                (".pptx", "PowerPoint Presentation"),
                (".ppt", "PowerPoint 97-2003 Presentation"),
                (".otp", "OpenDocument Presentation Template")]),
]

TEMPLATE = r'''; @@NAME@@ — Windows installer (NSIS). GENERATED by
; make-windows-installers.py — edit that, not this.
;
;   makensis -DENGINE_PAYLOAD=<dir> -DENGINE_VERSION=<ver> \
;            -DDISPLAYVERSION=<ver-rev> -DVIVERSION=<x.y.z.w> \
;            -DESTSIZE_KB=<du -sk> -DICOFILE=<ico> -DLAUNCHER=<cmd> \
;            -DLICENSEFILE=<file> -DNOTICEFILE=<file> -DOUTFILE=<path> <this>

Unicode true
!include "MUI2.nsh"

!define APPNAME "@@NAME@@"
!define APPKEY  "@@EXE@@"
!define MODULE  "@@MODULE@@"
!define SLUG    "@@SLUG@@"
!define PUBLISHER "QuickOpen"
!define APPURL "https://quickopen.ai/projects/@@SLUG@@"
!define UNINSTKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPKEY}"
!define QOKEY "Software\QuickOpen\QuickOffice"

Name "${APPNAME}"
OutFile "${OUTFILE}"
InstallDir "$PROGRAMFILES64\QuickOpen\Quick Office"
RequestExecutionLevel admin
; signed after build — see the app installers: CRC off, signature is integrity
CRCCheck off
SetCompressor /SOLID lzma
SetCompressorDictSize 64

VIProductVersion "${VIVERSION}"
VIAddVersionKey "ProductName" "${APPNAME}"
VIAddVersionKey "CompanyName" "${PUBLISHER}"
VIAddVersionKey "ProductVersion" "${DISPLAYVERSION}"
VIAddVersionKey "FileVersion" "${VIVERSION}"
VIAddVersionKey "FileDescription" "${APPNAME} installer"
VIAddVersionKey "LegalCopyright" "Engine: MPL-2.0 (a derivative of LibreOffice). QuickOpen layer: Apache-2.0."

!define MUI_ICON "${ICOFILE}"
!define MUI_UNICON "${ICOFILE}"
!insertmacro MUI_PAGE_LICENSE "${LICENSEFILE}"
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Quick Office engine"
  SetRegView 64
  SetShellVarContext all
  ; skip when this exact engine version is already installed (another Quick
  ; Office app put it there) — the whole point of the shared engine dir
  ReadRegStr $0 HKLM "${QOKEY}" "EngineVersion"
  StrCmp $0 "${ENGINE_VERSION}" 0 engine_install
  IfFileExists "$INSTDIR\program\soffice.exe" engine_ok engine_install
engine_install:
  DetailPrint "Installing the shared Quick Office engine ${ENGINE_VERSION}..."
  SetOutPath "$INSTDIR"
  File /r "${ENGINE_PAYLOAD}/*"
  WriteRegStr HKLM "${QOKEY}" "EnginePath" "$INSTDIR"
  WriteRegStr HKLM "${QOKEY}" "EngineVersion" "${ENGINE_VERSION}"
  Goto engine_done
engine_ok:
  DetailPrint "Shared Quick Office engine ${ENGINE_VERSION} already installed."
engine_done:
SectionEnd

Section "@@NAME@@"
  SetRegView 64
  SetShellVarContext all
  SetOutPath "$INSTDIR"
  File "${ICOFILE}"
  File "${LAUNCHER}"
  File "/oname=NOTICE-${APPKEY}" "${NOTICEFILE}"

  WriteUninstaller "$INSTDIR\Uninstall-${APPKEY}.exe"

  ; refcount: the engine stays while this key has any values
  WriteRegStr HKLM "${QOKEY}\Apps" "${SLUG}" "${DISPLAYVERSION}"

  ; shortcuts — Quick name + Quick icon, straight at the engine module
  CreateShortCut "$SMPROGRAMS\${APPNAME}.lnk" "$INSTDIR\program\soffice.exe" "${MODULE}" "$INSTDIR\@@SLUG@@.ico" 0 SW_SHOWNORMAL "" "@@COMMENT@@"
  CreateShortCut "$DESKTOP\${APPNAME}.lnk" "$INSTDIR\program\soffice.exe" "${MODULE}" "$INSTDIR\@@SLUG@@.ico" 0

  ; uninstall entry
  WriteRegStr HKLM "${UNINSTKEY}" "DisplayName" "${APPNAME}"
  WriteRegStr HKLM "${UNINSTKEY}" "DisplayVersion" "${DISPLAYVERSION}"
  WriteRegStr HKLM "${UNINSTKEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKLM "${UNINSTKEY}" "DisplayIcon" "$INSTDIR\@@SLUG@@.ico"
  WriteRegStr HKLM "${UNINSTKEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "${UNINSTKEY}" "URLInfoAbout" "${APPURL}"
  WriteRegStr HKLM "${UNINSTKEY}" "UninstallString" '"$INSTDIR\Uninstall-${APPKEY}.exe"'
  WriteRegStr HKLM "${UNINSTKEY}" "QuietUninstallString" '"$INSTDIR\Uninstall-${APPKEY}.exe" /S'
  WriteRegDWORD HKLM "${UNINSTKEY}" "NoModify" 1
  WriteRegDWORD HKLM "${UNINSTKEY}" "NoRepair" 1
  WriteRegDWORD HKLM "${UNINSTKEY}" "EstimatedSize" ${ESTSIZE_KB}

  ; file types (OpenWithProgids — never steals an existing default)
@@ASSOC@@
SectionEnd

Section "Uninstall"
  SetRegView 64
  SetShellVarContext all
  Delete "$SMPROGRAMS\${APPNAME}.lnk"
  Delete "$DESKTOP\${APPNAME}.lnk"
@@UNASSOC@@
  DeleteRegKey HKLM "${UNINSTKEY}"
  DeleteRegValue HKLM "${QOKEY}\Apps" "${SLUG}"
  ; last app out removes the shared engine; otherwise only this face leaves
  ClearErrors
  EnumRegValue $0 HKLM "${QOKEY}\Apps" 0
  IfErrors 0 keep_engine
  DetailPrint "No Quick Office apps left — removing the shared engine."
  DeleteRegKey HKLM "${QOKEY}"
  RMDir /r "$INSTDIR"
  Goto done
keep_engine:
  DetailPrint "Other Quick Office apps still installed — keeping the engine."
  Delete "$INSTDIR\@@SLUG@@.ico"
  Delete "$INSTDIR\@@SLUG@@.cmd"
  Delete "$INSTDIR\NOTICE-${APPKEY}"
  Delete "$INSTDIR\Uninstall-${APPKEY}.exe"
done:
SectionEnd
'''


def assoc_lines(app):
    add, remove = [], []
    for ext, desc in app["mimes"]:
        progid = f'{app["exe"]}{ext}'
        add.append(f'  WriteRegStr HKLM "Software\\Classes\\{ext}\\OpenWithProgids" "{progid}" ""')
        add.append(f'  WriteRegStr HKLM "Software\\Classes\\{progid}" "" "{desc}"')
        add.append(f'  WriteRegStr HKLM "Software\\Classes\\{progid}\\DefaultIcon" "" "$INSTDIR\\{app["slug"]}.ico"')
        add.append(f'  WriteRegStr HKLM "Software\\Classes\\{progid}\\shell\\open\\command" "" \'"$INSTDIR\\program\\soffice.exe" {app["module"]} "%1"\'')
        remove.append(f'  DeleteRegValue HKLM "Software\\Classes\\{ext}\\OpenWithProgids" "{progid}"')
        remove.append(f'  DeleteRegKey HKLM "Software\\Classes\\{progid}"')
    return "\n".join(add), "\n".join(remove)


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "build")
    os.makedirs(outdir, exist_ok=True)
    for app in APPS:
        name = " ".join(w.capitalize() for w in app["slug"].split("-"))
        assoc, unassoc = assoc_lines(app)
        nsi = (TEMPLATE
               .replace("@@NAME@@", name)
               .replace("@@EXE@@", app["exe"])
               .replace("@@SLUG@@", app["slug"])
               .replace("@@MODULE@@", app["module"])
               .replace("@@COMMENT@@", app["comment"])
               .replace("@@ASSOC@@", assoc)
               .replace("@@UNASSOC@@", unassoc))
        path = os.path.join(outdir, f'{app["exe"]}.nsi')
        with open(path, "w") as f:
            f.write(nsi)
        print(f"   {path}")


if __name__ == "__main__":
    main()
